FROM postgres:12-alpine

# Variables used by postgres image - defining user, password and database name
ENV POSTGRES_DB="dvdrental"
ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="secret"


RUN apk update && apk upgrade